// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKMnYJKk8T3u1DSk9ApXmBUCQtPyHL_XI',
    appId: '1:848203053924:web:b9f38a3f8e2ea18e4b9871',
    messagingSenderId: '848203053924',
    projectId: 'sport-brands-42c8a',
    authDomain: 'sport-brands-42c8a.firebaseapp.com',
    storageBucket: 'sport-brands-42c8a.firebasestorage.app',
    measurementId: 'G-5D87S9GLSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz3vlydpBIh8P1JJ7vFcNgfmLTfRfZ8l0',
    appId: '1:848203053924:android:7664d0352d3dd2934b9871',
    messagingSenderId: '848203053924',
    projectId: 'sport-brands-42c8a',
    storageBucket: 'sport-brands-42c8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7XVcNQC99Gb4gJCwKb1XTZF8PxDmR9aE',
    appId: '1:848203053924:ios:cd28cb961d82503e4b9871',
    messagingSenderId: '848203053924',
    projectId: 'sport-brands-42c8a',
    storageBucket: 'sport-brands-42c8a.firebasestorage.app',
    iosBundleId: 'com.example.shoeStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7XVcNQC99Gb4gJCwKb1XTZF8PxDmR9aE',
    appId: '1:848203053924:ios:cd28cb961d82503e4b9871',
    messagingSenderId: '848203053924',
    projectId: 'sport-brands-42c8a',
    storageBucket: 'sport-brands-42c8a.firebasestorage.app',
    iosBundleId: 'com.example.shoeStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKMnYJKk8T3u1DSk9ApXmBUCQtPyHL_XI',
    appId: '1:848203053924:web:ccd8729203b0e1874b9871',
    messagingSenderId: '848203053924',
    projectId: 'sport-brands-42c8a',
    authDomain: 'sport-brands-42c8a.firebaseapp.com',
    storageBucket: 'sport-brands-42c8a.firebasestorage.app',
    measurementId: 'G-HHRMDJD0ZS',
  );
}
